#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Mdoq\Pontoon\Command\Play;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new Play());

$application->run();